<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BankingApi.DTO\BankingApi.DTO.csproj" />
    <ProjectReference Include="..\BankingApi.Infrastructure\BankingApi.Infrastructure.csproj" />
    <ProjectReference Include="..\BankingApi.Shared\BankingApi.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
